api:
  port: 3000

# Default password and login for the admin panel. User with these credentials is generated on the start.
admin:
  login: admin
  password: admin

# Config for the main database
postgres:
  host: localhost
  port: 5432
  user: postgres
  dbName: crystalline
  password: postgres
  sslmode: disable
  sslCertificatePath: SSL_CERTIFICATE_PATH
  sslKeyPath: SSL_KEY_PATH
  sslRootCertificatePath: SSL_ROOT_CERTIFICATE_PATH

# Config for database used by RADIUS
radusDatabase:
  host: localhost
  port: 5432
  user: postgres
  dbName: radius
  password: postgres
  sslmode: disable
  sslCertificatePath: SSL_CERTIFICATE_PATH
  sslKeyPath: SSL_KEY_PATH
  sslRootCertificatePath: SSL_ROOT_CERTIFICATE_PATH

twilio:
  host: https://api.twilio.com/2010-04-01
  sid: TWILIO_SID
  token: TWILIO_ACCESS_TOKEN
  from: SENDER_NAME
  confirmationCodeMessageTemplate: Your confirmation code is %s
  voucherMessageTemplate: Your Wi-Fi voucher is %s

worldbit:
  apiKey: API_KEY
  apiSecret: API_SECRET
  merchantID: MERCHANT_ID
  host: https://api.worldbit.com/api/v1
  monitoringTimeout: 172800 # In seconds
  defaultCurrency: WBTx
  defaultEmail: default@email.com

paypal:
  host: https://api.sandbox.paypal.com/v1
  clientID: PAYPAL_CLIENT_ID
  secret: PAYPAL_SECRET

recaptcha:
  secret: GOOGLE_RECAPTCHA_SECRET

daemon: false

confirmationCodeExpiration: EXPIRATION_TIME_IN_SECONDS
